Repository open-telemetry/opentelemetry-js-api, pull requests merged in 2021-04, with the labels that each got.

#32 feat!: return boolean success value from setGlobalXXX methods
  src/api/context.ts
  src/api/diag.ts
  src/api/propagation.ts
  src/api/trace.ts
  src/internal/global-utils.ts
Labels: breaking

#44 chore: updating readme headline and fixing links
  README.md
Labels: documentation

#43 chore: renaming noop span to non recording span
  README.md
  src/context/context.ts
  src/trace/NonRecordingSpan.ts
  src/trace/NoopTracer.ts
  test/api/api.test.ts
  test/noop-implementations/noop-span.test.ts
  test/noop-implementations/noop-tracer.test.ts
  test/proxy-implementations/proxy-tracer.test.ts
Labels: breaking

#51 feat: add function to wrap SpanContext in NonRecordingSpan #49
  src/api/trace.ts
  src/trace/spancontext-utils.ts
  test/trace/spancontext-utils.test.ts
Labels: enhancement, specification

#48 chore: update dev-dependencies
  package.json
Labels: dependencies
