Repository open-telemetry/opentelemetry-js-api, pull requests merged in 2021-05, with the labels that each got.

#47 chore: move span method for context in trace API #40
  README.md
  src/api/trace.ts
  src/baggage/index.ts
  src/context/context.ts
  src/trace/NoopTracer.ts
  src/trace/context-utils.ts
  test/noop-implementations/noop-tracer.test.ts
  test/trace/context-utils.test.ts
Labels: breaking

#58 chore: use spancontext for link
  src/index.ts
  src/trace/link.ts
  src/trace/link_context.ts
Labels: breaking, enhancement, specification

#60 chore: removing timed event
  README.md
  src/index.ts
  src/trace/Event.ts
  src/trace/TimedEvent.ts
Labels: breaking, specification

#64 chore: document the reason for symbol.for
  src/context/context.ts
Labels: documentation

#65 chore: remove suppress instrumentation
  src/trace/context-utils.ts
  test/trace/context-utils.test.ts
Labels: breaking, specification

#55 chore: move baggage methods in propagation namespace
  README.md
  src/api/propagation.ts
  src/index.ts
  test/baggage/Baggage.test.ts
Labels: breaking

#54 feat: add tracer.startActiveSpan()
  src/trace/NoopTracer.ts
  src/trace/ProxyTracer.ts
  src/trace/tracer.ts
  test/noop-implementations/noop-tracer.test.ts
  test/proxy-implementations/proxy-tracer.test.ts
Labels: enhancement

#62 chore: adding component logger
  src/api/diag.ts
  src/diag/ComponentLogger.ts
  src/diag/types.ts
  test/diag/ComponentLogger.test.ts
Labels: enhancement

#71 chore: export baggage
  src/api/propagation.ts
  src/baggage/Entry.ts
  src/baggage/context-helpers.ts
  src/baggage/internal/baggage-impl.ts
  src/baggage/types.ts
  src/baggage/utils.ts
  src/index.ts
Labels: enhancement

#79 chore: fix eslint config
  .eslintrc.js
  backwards-compatability/node10/index.ts
  backwards-compatability/node10/tsconfig.json
  backwards-compatability/node12/index.ts
  backwards-compatability/node12/tsconfig.json
  backwards-compatability/node8/index.ts
  backwards-compatability/node8/tsconfig.json
Labels: internal

#46 chore: do not export singletons
  src/api/propagation.ts
  src/index.ts
  src/propagation/NoopTextMapPropagator.ts
  src/trace/NoopTracer.ts
  src/trace/NoopTracerProvider.ts
  src/trace/ProxyTracer.ts
  src/trace/ProxyTracerProvider.ts
  test/api/api.test.ts
  test/internal/global.test.ts
  test/noop-implementations/noop-tracer.test.ts
  test/proxy-implementations/proxy-tracer.test.ts
Labels: breaking
