Repository open-telemetry/opentelemetry-js-api, pull requests merged in 2021-06, with the labels that each got.

#81 chore: function overloads implementation of startActiveSpan in noop t…
  src/trace/NoopTracer.ts
  test/noop-implementations/noop-tracer.test.ts
Labels: enhancement

#84 chore: remove unused backwards compatibility folder
  .eslintrc.js
  backwards-compatability/node10/index.ts
  backwards-compatability/node10/package.json
  backwards-compatability/node10/tsconfig.json
  backwards-compatability/node12/index.ts
  backwards-compatability/node12/package.json
  backwards-compatability/node12/tsconfig.json
  backwards-compatability/node8/index.ts
  backwards-compatability/node8/package.json
  backwards-compatability/node8/tsconfig.json
Labels: internal

#78 feat: unify signatures of `with` and `bind`
  src/api/context.ts
  src/context/NoopContextManager.ts
  src/context/types.ts
  test/context/NoopContextManager.test.ts
Labels: breaking

#89 chore: update upgrade guidelines
  README.md
Labels: documentation

#93 chore: only report coverage on 14
  .github/workflows/test.yaml
Labels: internal
