Repository open-telemetry/opentelemetry-js-api, pull requests merged in 2021-07, with the labels that each got.

#94 chore: enforce strict equality on prerelease versions
  src/internal/semver.ts
  test/internal/semver.test.ts
Labels: enhancement

#100 chore: update dependencies
  package.json
Labels: dependencies

#101 docs: Format example for tracer.startActiveSpan
  src/trace/tracer.ts
Labels: documentation

#106 docs: fix crash in README example
  README.md
Labels: documentation

#109 internal: add missing approvers from core
  .github/CODEOWNERS
Labels: internal

#105 fix: set delegate after successful registration
  src/api/trace.ts
  test/api/api.test.ts
Labels: bug
