Repository open-telemetry/opentelemetry-js-api, pull requests merged in 2021-08, with the labels that each got.

#112 chore: add release-please github action
  .github/workflows/release-please.yml
  .gitignore
  package.json
  src/version.ts
Labels: internal

#113 docs: Use semantic conventions and correct span status in tracing.md
  docs/tracing.md
Labels: documentation

#119 fix: remove all circular dependencies
  .github/workflows/lint.yaml
  package.json
  src/baggage/utils.ts
  src/index.ts
  src/internal/global-utils.ts
  src/trace/NonRecordingSpan.ts
  src/trace/NoopTracer.ts
  src/trace/ProxyTracer.ts
  src/trace/invalid-span-constants.ts
  src/trace/spancontext-utils.ts
  test/trace/spancontext-utils.test.ts
Labels: bug

#120 chore: release 1.0.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending
