Repository open-telemetry/opentelemetry-js-api, pull requests merged in 2022-01, with the labels that each got.

#147 Add TraceState implementation to API
  src/index.ts
  src/trace/internal/tracestate-impl.ts
  src/trace/internal/tracestate-validators.ts
  src/trace/internal/utils.ts
  test/trace/tracestate-validators.test.ts
  test/trace/tracestate.test.ts
Labels: enhancement

#154 fix: export tracer options
  src/index.ts
Labels: bug

#155 docs: add notes on attribute key descriptor
  src/common/Attributes.ts
  src/trace/attributes.ts
Labels: documentation

#151 chore: release 1.1.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
